import _ from 'lodash'
import JSON5 from 'json5'
window.JSON5 = JSON5

let game_items = [
    {id: 1000,
        name:'Water',
        type:'RESOURCE',
        grid_index:1107,
        stack_size:20,
        is_fluid:true,
        unlock_key:2306,
        mining_from:'Ocean',
        description:'It can be obtained from a water pump and widely used in chemical production.',
    },
    {id: 1001,
        name:'Iron Ore',
        type:'RESOURCE',
        grid_index:1101,
        stack_size:100,
        unlock_key:-1,
        mining_from:'Iron veins',
        description:'Used to smelt iron ingots and magnets. Obtained by gathering iron vein.<br>',
    },
    {id: 1002,
        name:'Copper Ore',
        type:'RESOURCE',
        grid_index:1102,
        stack_size:100,
        unlock_key:-1,
        mining_from:'Copper veins',
        description:'Smelted directly into copper ingots. Obtained by gathering copper vein. ',
    },
    {id: 1003,
        name:'Silicon Ore',
        type:'RESOURCE',
        grid_index:1105,
        stack_size:100,
        unlock_key:6001,
        mining_from:'Silicon veins',
        description:'Obtained by gathering from silicon veins. It is usually used to make high-purity silicon crystals.',
    },
    {id: 1004,
        name:'Titanium Ore',
        type:'RESOURCE',
        grid_index:1106,
        stack_size:100,
        unlock_key:6002,
        mining_from:'Titanium veins',
        description:'Can form under the action of high-intensity heat with a  particular molecular structure.',
    },
    {id: 1005,
        name:'Stone',
        type:'RESOURCE',
        grid_index:1103,
        stack_size:100,
        unlock_key:-1,
        mining_from:'Stone veins',
        description:'A common ore. It is a raw material which can be also obtained from rocks.',
    },
    {id: 1006,
        name:'Coal',
        type:'RESOURCE',
        grid_index:1104,
        stack_size:100,
        energy:2700000,
        fuel_chamber_boost:0.0,
        unlock_key:-1,
        mining_from:'Coal veins',
        description:"A solid combustible mineral. It's gradually formed by plants through complex biochemical, physical and chemical changes. It is raw material for smelting and chemical production as well as an energy source.",
    },
    {id: 1007,
        name:'Crude Oil',
        type:'RESOURCE',
        grid_index:1108,
        stack_size:20,
        is_fluid:true,
        energy:4050000,
        fuel_chamber_boost:0.2,
        unlock_key:2307,
        mining_from:'Crude oil seep',
        description:'Fossil formed by marine organisms can gather as a liquid mineral deposit. It contains the chemical energy marine organisms accumulated during their lifetime. Can as fuel or chemical raw material.<br>',
    },
    {id: 1011,
        name:'Fire Ice',
        type:'RESOURCE',
        grid_index:1307,
        stack_size:50,
        energy:4800000,
        fuel_chamber_boost:0.4,
        unlock_key:1120,
        mining_from:'Fire ice vein <span style:"color:#FFFFFFC1">(rare)</span>',
        description:'Rare ore. Has cage-like microstructure which is similar to ice-like white solid, and covalent bonds in a critical state allow it to be used to produce graphene more efficiently.',
    },
    {id: 1012,
        name:'Kimberlite Ore',
        type:'RESOURCE',
        grid_index:1112,
        stack_size:50,
        unlock_key:1112,
        mining_from:'Kimberlite vein <span style:"color:#B9DFFFC4">(rare)</span>',
        description:'Rare ore. Directly crystallized from Kimberlite magma under CO₂ rich conditions, and diamond can be obtained by further smelting.',
    },
    {id: 1013,
        name:'Fractal Silicon',
        type:'RESOURCE',
        grid_index:1212,
        stack_size:50,
        unlock_key:1105,
        mining_from:'Fractal silicium vein <span style:"color:#43FF89D4">(rare)</span>',
        description:'It is a rare natural silicon ore with a unique geometric fractal structure. After the single crystal grows to a certain size, the branches of smaller silicon crystals grow from the matrix. Crystal fractal is a natural purification mechanism. The more fractal algebra, the higher the purity. Among them, fractal silicon with more than six generations can directly be used as the raw material for making lattice silicon.',
    },
    {id: 1014,
        name:'Optical Grating Crystal',
        type:'RESOURCE',
        grid_index:1312,
        stack_size:50,
        unlock_key:6002,
        mining_from:'Optical grating crystal vein <span style:"color:#E37AFFDA">(rare)</span>',
        description:'Rare ore. With naturally formed grooves distributed on the surface, is used to produce precision optical components and high-power exciters.',
    },
    {id: 1015,
        name:'Spiniform Stalagmite Crystal',
        type:'RESOURCE',
        grid_index:1412,
        stack_size:50,
        unlock_key:6002,
        mining_from:'Spiniform stalagmite crystal vein <span style:"color:#7AF0FFC8">(rare)</span>',
        description:'It will only be a rare occurrence on the living planet that once existed widely in the ocean with a depth of 100,000 meters. After the marine life on these planets die, and the corpse sinks to the bottom of the sea, it can directly mineralize with seawater under the deep sea high pressure. If there is a stable, smooth, slow, and hot ocean current at this time, spiniform stalagmite crystal may form under the blow of the ocean current.',
    },
    {id: 1016,
        name:'Unipolar Magnet',
        type:'RESOURCE',
        grid_index:1512,
        stack_size:50,
        unlock_key:1206,
        mining_from:'Unipolar magnet vein <span style:"color:#FFA086C8">(rare)</span>',
        description:"Rare ore, Has a pyrochlore lattice. After applying a magnetic field, we can affect the string's symmetry and direction, reduce the string network's density, and separating magnetic monopoles.",
    },
    {id: 1030,
        name:'Log',
        type:'RESOURCE',
        grid_index:1612,
        stack_size:100,
        energy:1500000,
        fuel_chamber_boost:-0.1,
        unlock_key:-1,
        mining_from:'Tree',
        description:'Ordinary fuel. Obtained from trees, has low energy.',
    },
    {id: 1031,
        name:'Plant Fuel',
        type:'RESOURCE',
        grid_index:1712,
        stack_size:500,
        energy:500000,
        fuel_chamber_boost:-0.3,
        unlock_key:-1,
        mining_from:'Plant',
        description:'Compared with wood, although the energy is lower, it is easier to obtain.',
    },
    {id: 1101,
        name:'Iron Ingot',
        type:'MATERIAL',
        grid_index:1201,
        stack_size:100,
        description:'Basic raw material. Used to produce various iron components.',
    },
    {id: 1102,
        name:'Magnet',
        type:'MATERIAL',
        grid_index:1301,
        stack_size:200,
        description:'Basic magnetic material. Obtained by smelting iron ore directly.',
    },
    {id: 1103,
        name:'Steel',
        type:'MATERIAL',
        grid_index:1401,
        stack_size:100,
        description:'Under strict and controllable temperature conditions, using iron ingots as raw material for further smelting, the crystal form of the material is improved so that it has better mechanical properties.',
    },
    {id: 1104,
        name:'Copper Ingot',
        type:'MATERIAL',
        grid_index:1202,
        stack_size:100,
        description:'Basic raw material. Used to produce various copper components.',
    },
    {id: 1105,
        name:'High-Purity Silicon',
        type:'MATERIAL',
        grid_index:1205,
        stack_size:100,
        description:'After the crude silicon is melted and recrystallized, it can obtain analytically pure silicon crystals. The photovoltaic materials and semiconductor components made can fit a variety of needs.',
    },
    {id: 1106,
        name:'Titanium Ingot',
        type:'MATERIAL',
        grid_index:1206,
        stack_size:100,
        description:'Obtained from smelting titanium ores, it is light in weight and high in strength. It is an indispensable raw material for producing high-strength materials.',
    },
    {id: 1107,
        name:'Titanium Alloy',
        type:'MATERIAL',
        grid_index:1306,
        stack_size:100,
        description:"Under different temperatures, utilizing the characteristics of the titanium's lattice structure and adding precise proportions of alloying elements will produce a new type of alloy material that achieves a perfect balance of phase transition temperature and phase content. It has superior strength and toughness.",
    },
    {id: 1108,
        name:'Stone Brick',
        type:'MATERIAL',
        grid_index:1203,
        stack_size:100,
        description:'A common material. Obtained from smelting stone ores, is usually used as a foundation for facilities.',
    },
    {id: 1109,
        name:'Energetic Graphite',
        type:'MATERIAL',
        grid_index:1204,
        stack_size:100,
        energy:6750000,
        fuel_chamber_boost:0.5,
        explicit_tech_dep:1402,
        description:'Purify raw coal to obtain graphite, a more usable form of carbon. You can further compact graphite to create crystal diamonds that have more advanced applications.',
    },
    {id: 1110,
        name:'Glass',
        type:'MATERIAL',
        grid_index:1303,
        stack_size:100,
        description:'An amorphous optical medium material with an irregular structure, can be used to make various optical components such as prisms and lenses. And can also be used to make facilities and buildings.',
    },
    {id: 1111,
        name:'Prism',
        type:'MATERIAL',
        grid_index:1403,
        stack_size:100,
        description:'A polyhedron surrounded by two intersecting glass planes, can split light or disperse light beams. It is a key component for producing more precise optical instruments.',
    },
    {id: 1112,
        name:'Diamond',
        type:'MATERIAL',
        grid_index:1304,
        stack_size:100,
        energy:900000,
        fuel_chamber_boost:-0.5,
        description:'Diamond is obtained by using strong pressure and heat to change the structure of graphite. It is a very hard crystal that not only retains the parallel hexagonal lattice of graphite but also forms a cubic hexagonal lattice. ',
    },
    {id: 1113,
        name:'Crystal Silicon',
        type:'MATERIAL',
        grid_index:1305,
        stack_size:100,
        explicit_tech_dep:1403,
        description:'Obtain a spectrally pure silicon crystal after the High-purity silicon is melted and passed through a strong electric field at a certain speed, which can further remove the ionic impurities dissolved therein. Crystal silicon has almost no crystal defects and is mainly used to make some ultra-high-precision optical instruments.',
    },
    {id: 1114,
        name:'Refined Oil',
        type:'MATERIAL',
        grid_index:1208,
        stack_size:20,
        is_fluid:true,
        energy:4500000,
        fuel_chamber_boost:0.3,
        description:'The primary product of crude oil refining. A chemical fuel, can be used to produce various chemical products.',
    },
    {id: 1115,
        name:'Plastic',
        type:'MATERIAL',
        grid_index:1308,
        stack_size:100,
        description:'Primary chemical product. Has a wide range of uses and is usually used to make more advanced chemical products.',
    },
    {id: 1116,
        name:'Sulfuric Acid',
        type:'MATERIAL',
        grid_index:1207,
        stack_size:20,
        is_fluid:true,
        mining_from:'Sulfuric acid ocean',
        description:'Primary chemical product. Produced from crude oil, can also be directly gathered from the sea of sulfuric acid with a water pump.',
    },
    {id: 1117,
        name:'Organic Crystal',
        type:'MATERIAL',
        grid_index:1309,
        stack_size:100,
        energy:1800000,
        fuel_chamber_boost:-0.2,
        mining_from:'Organic crystal vein <span style:"color:#F5FF4FC1">(rare)</span>',
        description:'A high-grade chemical product. Used to produce higher strength crystals with a crystal structure. It can also be directly gathered from rare organic crystal vein.',
    },
    {id: 1118,
        name:'Titanium Crystal',
        type:'MATERIAL',
        grid_index:1409,
        stack_size:100,
        description:'Further, strengthen the lattice structure of titanium to form particular titanium atom crystal with higher strength by adding a precise proportion of organic crystals to titanium. ',
    },
    {id: 1119,
        name:'Titanium Glass',
        type:'MATERIAL',
        grid_index:1509,
        stack_size:100,
        description:'When the glass is in a molten state, adding a certain proportion of titanium can greatly strengthen the glass and adapt to more intense environments.',
    },
    {id: 1120,
        name:'Hydrogen',
        type:'MATERIAL',
        grid_index:1109,
        stack_size:20,
        is_fluid:true,
        energy:9000000,
        fuel_chamber_boost:1.0,
        explicit_tech_dep:1102,
        mining_from:'Gas giant orbit',
        description:'The most abundant element in the universe is the lightest gas.',
    },
    {id: 1121,
        name:'Deuterium',
        type:'MATERIAL',
        grid_index:1110,
        stack_size:20,
        is_fluid:true,
        energy:9000000,
        fuel_chamber_boost:1.0,
        unlock_key:1120,
        explicit_tech_dep:1134,
        mining_from:'Gas giant orbit',
        description:'A stable isotope of hydrogen. Rarely exists under natural conditions. Most of them come from the reprocessing of hydrogen and the collection from the Gas giant.',
    },
    {id: 1122,
        name:'Antimatter',
        type:'MATERIAL',
        grid_index:1111,
        stack_size:20,
        description:'It is obtained by inverting photons in a critical state. When the positive and antimatter meet, they will annihilate each other and generate huge energy.',
    },
    {id: 1123,
        name:'Graphene',
        type:'MATERIAL',
        grid_index:1310,
        stack_size:100,
        energy:96000,
        fuel_chamber_boost:-0.7,
        description:'The double-layer graphenes will form a complex repeating structure, a superlattice by rotating when stacking one layer of graphene on top of another. After rotating to a certain Magic Angle, double-layered graphene will gain superconductive properties. Graphene has become a new type of nano-superconducting material.',
    },
    {id: 1124,
        name:'Carbon Nanotube',
        type:'MATERIAL',
        grid_index:1410,
        stack_size:100,
        energy:84000,
        fuel_chamber_boost:-0.8,
        description:'The weight is very light with a perfectly connected hexagonal structure, has extremely high strength and strong resistance to deformation, and is usually used to manufacture high-efficiency devices.',
    },
    {id: 1125,
        name:'Frame Material',
        type:'MATERIAL',
        grid_index:1709,
        stack_size:100,
        description:'A new type of high-strength lightweight structure. Can withstand the strong gravitational force of stars compared with traditional structural materials, and is very suitable for manufacturing Dyson sphere components.',
    },
    {id: 1126,
        name:'Casimir Crystal',
        type:'MATERIAL',
        grid_index:1407,
        stack_size:100,
        description:'Use a strong electric field to fix the charged particles, and the Coulomb repulsion between the particles will spontaneously form a spatial ring-shaped ion crystal. After applying a weak static magnetic field, the zero-point energy of the particles inside the crystal is excited, producing an obvious Casimir effect.',
    },
    {id: 1127,
        name:'Strange Matter',
        type:'MATERIAL',
        grid_index:1408,
        stack_size:100,
        description:'Strange matter has a great gravitational negative pressure, which exceeds its energy density, so that the space around the strange matter is warped and meets the negative energy demand of the warp engine.',
    },
    {id: 1131,
        name:'Foundation',
        type:'COMPONENT',
        grid_index:1601,
        stack_size:1000,
        can_build:true,
        build_index:901,
        description:'A surface leveling tool. Cannot use it to change the planetary landforms at will, can only level the surface to zero altitude. If you use the foundation for high ground, you will get soil pile; on the contrary, if you use the foundation for the ocean or low-lying areas, you must consume soil pile. When laying the foundation, you can choose a kind of decoration, or without decoration, only level the surface.',
    },
    {id: 1141,
        name:'Proliferator Mk.I',
        type:'MATERIAL',
        grid_index:1406,
        stack_size:200,
        description:'Input the Proliferator into the Spray Coater from the conveyor belt port above the Spray Coater and it will be sprayed on the cargos. When the sprayed cargos are used as raw materials to produce the next-level products, it can obtain Extra Products or Production Speedup, it will also increase the power consumption.',
    },
    {id: 1142,
        name:'Proliferator Mk.II',
        type:'MATERIAL',
        grid_index:1506,
        stack_size:200,
        description:'Comparing with Proliferator MK.I, Proliferator MK.II upgraded the raw material formula. If you spray it on the cargos, when the sprayed cargos are used as raw materials to produce the next-level products, the effect of Extra Products or Production Speedup will be improved.',
    },
    {id: 1143,
        name:'Proliferator Mk.III',
        type:'MATERIAL',
        grid_index:1606,
        stack_size:200,
        description:'The raw material formula of the Proliferator has been furtherly upgraded. When the sprayed cargos are used as raw materials to produce the next-level products, it can maximize the effect of Extra Products or Production Speedup. The power consumption will also be greatly increased, and the requirements for the entire production line will be higher. ',
    },
    {id: 1201,
        name:'Gear',
        type:'COMPONENT',
        grid_index:1501,
        stack_size:200,
        description:'Standard component is used for transmission and other functions and is also widely used in various mechanical structures.',
    },
    {id: 1202,
        name:'Magnetic Coil',
        type:'COMPONENT',
        grid_index:1302,
        stack_size:200,
        description:'The most basic electromagnetic component. It is very functional.',
    },
    {id: 1203,
        name:'Electric Motor',
        type:'COMPONENT',
        grid_index:1404,
        stack_size:100,
        description:'The fundamental power system component. It can accelerate mechanical operation.',
    },
    {id: 1204,
        name:'Electromagnetic Turbine',
        type:'COMPONENT',
        grid_index:1504,
        stack_size:100,
        description:'Make objects levitate against gravity, usually used to make more advanced magnetic field generators.',
    },
    {id: 1205,
        name:'Super-Magnetic Ring',
        type:'COMPONENT',
        grid_index:1604,
        stack_size:100,
        description:'Super magnetic field generating device. Generated super-strong magnetic field can directly act on the atomic scale, causing the distortion of the material lattice, thereby preparing high-performance materials and devices.',
    },
    {id: 1206,
        name:'Particle Container',
        type:'COMPONENT',
        grid_index:1603,
        stack_size:100,
        description:'While firmly binding the particles, it can guide particles to show some specific properties.',
    },
    {id: 1208,
        name:'Critical Photon',
        type:'MATERIAL',
        grid_index:1602,
        stack_size:100,
        unlock_key:1122,
        explicit_tech_dep:1506,
        explicit_produce_from:'Ray Receiver',
        description:'A critical state photon. Can be converted into antimatter and hydrogen under the action of a super magnetic field.',
    },
    {id: 1209,
        name:'Graviton Lens',
        type:'COMPONENT',
        grid_index:1605,
        stack_size:100,
        description:'A piece of neutron star material that has been encapsulated after processing, its twisted and powerful gravitational field is shielded in a container. Usually, we will use it to process and change the spatial structure, but we can expect some one use it to refract the sunlight and ignite fire.',
    },
    {id: 1210,
        name:'Space Warper',
        type:'COMPONENT',
        grid_index:1608,
        stack_size:100,
        explicit_tech_dep:1704,
        description:'Consumables. Used to activate warp of mecha and logistics vessels.<br>Use the <span style:"color:#FD965ECC">CapsLock</span> key to start the warp engine.',
    },
    {id: 1301,
        name:'Circuit Board',
        type:'COMPONENT',
        grid_index:1402,
        stack_size:200,
        description:'The most basic electrical component. It is very versatile.',
    },
    {id: 1302,
        name:'Microcrystalline Component',
        type:'COMPONENT',
        grid_index:1405,
        stack_size:200,
        description:'Microcrystalline component is the basis for processors to achieve high-speed computing functions. It requires carving and processing city-like three-dimensional nanostructures on high-purity silicon wafers to make.',
    },
    {id: 1303,
        name:'Processor',
        type:'COMPONENT',
        grid_index:1505,
        stack_size:200,
        description:'Large-scale integrated circuit device. The application of semiconductor materials make it better in processing data and controlling the processing process.',
    },
    {id: 1304,
        name:'Plane Filter',
        type:'COMPONENT',
        grid_index:1609,
        stack_size:200,
        description:'Studying the Rabi oscillation to obtain the law of the probability change with time during the evolution of the particle wave function over time, it can be artificially interfered with during the quantum transition so that the quantum jumps in the expected direction.',
    },
    {id: 1305,
        name:'Quantum Chip',
        type:'COMPONENT',
        grid_index:1610,
        stack_size:200,
        description:'With powerful computing power and ultra-fast computing speed, it can warn whether the quantum transition will cause errors. And timely prevent its transition by reversing the transition process that may cause errors.',
    },
    {id: 1401,
        name:'Plasma Exciter',
        type:'COMPONENT',
        grid_index:1502,
        stack_size:200,
        description:'The plasma generated by the high-power exciter can be used to extract and refine crude oil, and can also be used to make wireless power tower for remote power transmission and charge mecha.',
    },
    {id: 1402,
        name:'Particle Broadband',
        type:'COMPONENT',
        grid_index:1510,
        stack_size:200,
        description:'Control the particles to maintain a certain regularity, which greatly improves the printing speed of the particles.',
    },
    {id: 1403,
        name:'Annihilation Constraint Sphere',
        type:'COMPONENT',
        grid_index:1508,
        stack_size:20,
        description:'It is a crucial component of artificial stars to confine the annihilation reaction within the sphere to obtain stable and controllable energy output.',
    },
    {id: 1404,
        name:'Photon Combiner',
        type:'COMPONENT',
        grid_index:1503,
        stack_size:200,
        description:'The surface of the prism is cut into nano-gratings and then reassembled. After continuously absorbing multiple low-energy photons will emit a high-energy photon under a combination of specific structures. The magic is that the natural Optical grating crystal in the cluster can directly do this.',
    },
    {id: 1405,
        name:'Thruster',
        type:'COMPONENT',
        grid_index:1311,
        stack_size:200,
        description:'Can provide power for logistics drone.',
    },
    {id: 1406,
        name:'Reinforced Thruster',
        type:'COMPONENT',
        grid_index:1411,
        stack_size:100,
        description:'It is an upgraded version of the thruster that can power the logistics vessel.',
    },
    {id: 1501,
        name:'Solar Sail',
        type:'PRODUCT',
        grid_index:1708,
        stack_size:200,
        description:'Use the EM-Rail Ejector to launch a large number of solar sails to form Dyson swarm, which can more effectively obtain the radiant energy of stars.',
    },
    {id: 1502,
        name:'Dyson Sphere Component',
        type:'COMPONENT',
        grid_index:1710,
        stack_size:100,
        description:'Use a small carrier rocket to transport them to the planned Dyson sphere to form the nodes and frames of the Dyson sphere.',
    },
    {id: 1503,
        name:'Small Carrier Rocket',
        type:'PRODUCT',
        grid_index:1711,
        stack_size:20,
        description:'The delivery vehicle of Dyson sphere components. If you want to speed up the construction, you need to send more rockets.',
    },
    {id: 1801,
        name:'Hydrogen Fuel Rod',
        type:'PRODUCT',
        grid_index:1209,
        stack_size:30,
        energy:54000000,
        fuel_chamber_boost:2.0,
        description:"With further development of cryo-technology hydrogen can be liquefied to make fuel rods for higher combustion efficiency. These higher energy Fuel Rods can greatly increase the mecha's fuel power generation.",
    },
    {id: 1802,
        name:'Deuteron Fuel Rod',
        type:'PRODUCT',
        grid_index:1210,
        stack_size:30,
        energy:600000000,
        fuel_chamber_boost:3.0,
        description:'Under a magnetic field, it is possible to make deuterium into deuteron fuel rods as a better source of energy. These fuel rods are often used in small fusion systems.',
    },
    {id: 1803,
        name:'Antimatter Fuel Rod',
        type:'PRODUCT',
        grid_index:1211,
        stack_size:30,
        energy:7200000000,
        fuel_chamber_boost:5.0,
        description:'Antimatter can be made into a more stable fuel rod by using the strong restraint of annihilation constraint sphere. It will be safer in this way.',
    },
    {id: 2001,
        name:'Conveyor Belt MK.I',
        type:'LOGISTICS',
        grid_index:2201,
        stack_size:300,
        sub_id:1,
        can_build:true,
        build_index:301,
        description:'We need automation! Conveyor belts are the most basic part of production automation. They can transport cargo from one place to another.',
    },
    {id: 2002,
        name:'Conveyor Belt MK.II',
        type:'LOGISTICS',
        grid_index:2202,
        stack_size:300,
        sub_id:2,
        can_build:true,
        build_index:302,
        description:'An upgraded conveyor belt, with higher speed and consequently higher throughput.',
    },
    {id: 2003,
        name:'Conveyor Belt MK.III',
        type:'LOGISTICS',
        grid_index:2203,
        stack_size:300,
        sub_id:3,
        can_build:true,
        build_index:303,
        description:'Maximize the speed and throughput of transporting cargo.',
    },
    {id: 2011,
        name:'Sorter MK.I',
        type:'LOGISTICS',
        grid_index:2301,
        stack_size:200,
        sub_id:1,
        can_build:true,
        build_index:304,
        description:'Transport cargo from conveyor belts into facilities or between facilities, can install filter to filter the cargo.',
    },
    {id: 2012,
        name:'Sorter MK.II',
        type:'LOGISTICS',
        grid_index:2302,
        stack_size:200,
        sub_id:2,
        can_build:true,
        build_index:305,
        description:'Can sort cargo more quickly.',
    },
    {id: 2013,
        name:'Sorter MK.III',
        type:'LOGISTICS',
        grid_index:2303,
        stack_size:200,
        sub_id:3,
        can_build:true,
        build_index:306,
        description:'In order to maximize the speed of sorting cargo, we can upgrade technology to increase the number of cargo that can be transported by the sorter MK.III each time.',
    },
    {id: 2020,
        name:'Splitter',
        type:'LOGISTICS',
        grid_index:2204,
        stack_size:50,
        can_build:true,
        build_index:307,
        description:'Used to distribute cargo to different conveyor belts, or to balance multiple conveyor belts. Can set the filter and priority on any one port.',
    },
    {id: 2030,
        name:'Traffic Monitor',
        type:'LOGISTICS',
        grid_index:2206,
        stack_size:100,
        can_build:true,
        build_index:309,
        description:'The Traffic Monitor is built on the conveyor belt to monitor the real-time cargo flow rate at the corresponding location. Conditions can be set to trigger an alarm.',
    },
    {id: 2040,
        name:'Automatic Piler',
        type:'LOGISTICS',
        grid_index:2205,
        stack_size:50,
        can_build:true,
        build_index:308,
        description:'After setting up the Automatic Piler on the conveyor belt, it can automatically integrate two consecutive cargos into one, which greatly improves the carrying capacity of the conveyor belt.',
    },
    {id: 2101,
        name:'Storage MK.I',
        type:'LOGISTICS',
        grid_index:2207,
        stack_size:50,
        sub_id:1,
        can_build:true,
        build_index:401,
        description:'Used to store products, but the capacity is limited.',
    },
    {id: 2102,
        name:'Storage MK.II',
        type:'LOGISTICS',
        grid_index:2208,
        stack_size:50,
        sub_id:2,
        can_build:true,
        build_index:402,
        description:'Has twice the capacity of a Storage Mk.I and requires steel to produce.',
    },
    {id: 2103,
        name:'Planetary Logistics Station',
        type:'LOGISTICS',
        grid_index:2210,
        stack_size:10,
        can_build:true,
        build_index:601,
        description:'The hub of the planetary logistics system. Logistics drones will automatically transport cargo between stations when you set the corresponding items for supply and demand. <br>(Only enables delivery around its own planet.)',
    },
    {id: 2104,
        name:'Interstellar Logistics Station',
        type:'LOGISTICS',
        grid_index:2211,
        stack_size:10,
        can_build:true,
        build_index:602,
        description:'The magnificent space elevator realizes more convenient transportation of materials between planets. It can connect factories on different planets to form a gigantic industrial empire.',
    },
    {id: 2105,
        name:'Orbital Collector',
        type:'LOGISTICS',
        grid_index:2212,
        stack_size:10,
        can_build:true,
        build_index:603,
        description:'Used to collect the resources of the gas giants, it needs to consume the collected fuel materials to maintain the energy required to work in orbit.',
    },
    {id: 2106,
        name:'Storage Tank',
        type:'LOGISTICS',
        grid_index:2209,
        stack_size:50,
        can_build:true,
        build_index:403,
        description:'The Storage Tank has a larger capacity than the Storage for storing fluid. When dismantling a non-empty Storage Tank any remaining fluid will be lost.',
    },
    {id: 2201,
        name:'Tesla Tower',
        type:'LOGISTICS',
        grid_index:2101,
        stack_size:100,
        sub_id:1,
        can_build:true,
        build_index:101,
        description:'The power transmission facility. Can extend the power supply range of the power grid with a certain connection length and supply area.',
    },
    {id: 2202,
        name:'Wireless Power Tower',
        type:'LOGISTICS',
        grid_index:2102,
        stack_size:100,
        sub_id:2,
        can_build:true,
        build_index:102,
        description:'Remote transmission facility. Can consume electricity from the power grid to charge the mecha.',
    },
    {id: 2203,
        name:'Wind Turbine',
        type:'PRODUCTION',
        grid_index:2104,
        stack_size:50,
        sub_id:4,
        can_build:true,
        build_index:104,
        description:"The primary power facility. Can convert wind energy into electrical energy. The actual generation capacity is related to the planet's wind energy ratio.",
    },
    {id: 2204,
        name:'Thermal Power Plant',
        type:'PRODUCTION',
        grid_index:2105,
        stack_size:50,
        sub_id:5,
        can_build:true,
        build_index:105,
        description:'Facility that uses combustible materials (such as coal) as fuel to generate electrical energy. Energy loss between the energy value of the provided fuel and the produced electricity is expected.',
    },
    {id: 2205,
        name:'Solar Panel',
        type:'PRODUCTION',
        grid_index:2106,
        stack_size:50,
        sub_id:7,
        can_build:true,
        build_index:106,
        description:"Directly generate electricity using sunlight, and the actual generation capacity is related to the planet's solar energy ratio. Not working at night, use accumulators can store excess energy during the day.",
    },
    {id: 2206,
        name:'Accumulator',
        type:'LOGISTICS',
        grid_index:2410,
        stack_size:50,
        sub_id:8,
        can_build:true,
        build_index:109,
        description:'Power storage facility. When the electricity of the power grid is surplus, it will automatically store the excess power. When the power supply is insufficient, it will automatically discharge to maintain the operation of the facilities.',
    },
    {id: 2207,
        name:'Accumulator(Full)',
        type:'LOGISTICS',
        grid_index:2411,
        stack_size:50,
        sub_id:8,
        can_build:true,
        energy:270000000,
        fuel_chamber_boost:1.0,
        unlock_key:2206,
        explicit_tech_dep:1511,
        explicit_produce_from:'Energy Exchanger',
        description:'The accumulator in the fully charged state. When the power is insufficient, can be constructed as a facility to automatically discharge, or it can be placed in an energy exchanger to release electrical energy.',
    },
    {id: 2208,
        name:'Ray Receiver',
        type:'PRODUCTION',
        grid_index:2110,
        stack_size:20,
        sub_id:9,
        can_build:true,
        build_index:802,
        description:'Receives high-energy rays transmitted from the Dyson swarm or Dyson sphere. The received energy can be directly outputted to the power grid, or stored as photons in a critical state.',
    },
    {id: 2209,
        name:'Energy Exchanger',
        type:'LOGISTICS',
        grid_index:2109,
        stack_size:20,
        sub_id:10,
        can_build:true,
        build_index:604,
        description:'The power conversion facility. Can not only store the surplus electric energy in the power grid into an empty accumulator to make a full accumulator; it can also release the electric energy stored in the full accumulator.',
    },
    {id: 2210,
        name:'Artificial Star',
        type:'PRODUCTION',
        grid_index:2111,
        stack_size:20,
        sub_id:11,
        can_build:true,
        build_index:804,
        description:'"All you have to do is let the positive and negative proton beams quietly cross the magnetic field from both ends into the constraint sphere, nice\'n easy!" This scaled-down version of the system is known as the Mini-sun.<br>',
    },
    {id: 2211,
        name:'Mini Fusion Power Plant',
        type:'PRODUCTION',
        grid_index:2108,
        stack_size:50,
        sub_id:6,
        can_build:true,
        build_index:108,
        description:'Under the action of a high-strength, high-density magnetic field, this facility converts the huge energy released by the controlled fusion reaction of Deuteron fuel rods into electrical energy.',
    },
    {id: 2212,
        name:'Satellite Substation',
        type:'LOGISTICS',
        grid_index:2103,
        stack_size:30,
        sub_id:3,
        can_build:true,
        build_index:103,
        description:'Wide-area power distribution facility. Provides longer range power transmission and a larger power supply area.',
    },
    {id: 2213,
        name:'Geothermal Power Station',
        type:'PRODUCTION',
        grid_index:2107,
        stack_size:50,
        sub_id:12,
        can_build:true,
        build_index:107,
        description:'A power generation facility using magma as an energy source. Combine multiple consecutive low-energy photons into one high-energy photon, and input energy to the grid stably. The power generation is directly related to the concentration of magma.',
    },
    {id: 2301,
        name:'Mining Machine',
        type:'PRODUCTION',
        grid_index:2304,
        stack_size:50,
        sub_id:1,
        can_build:true,
        build_index:201,
        description:'The more veins covered by the mining machine, the faster the mining speed, and the same vein can be covered by multiple mining rings, but the more mining rings covered, the faster the consumption.',
    },
    {id: 2302,
        name:'Arc Smelter',
        type:'PRODUCTION',
        grid_index:2404,
        stack_size:50,
        can_build:true,
        build_index:501,
        description:'High temperature arc smelting can smelt ores and metals, and also be used for purification and crystal smelting.',
    },
    {id: 2303,
        name:'Assembling Machine Mk.I',
        type:'PRODUCTION',
        grid_index:2401,
        stack_size:50,
        can_build:true,
        build_index:503,
        description:'The basic assembler. Can process iron and copper ingots into more advanced products.',
    },
    {id: 2304,
        name:'Assembling Machine Mk.II',
        type:'PRODUCTION',
        grid_index:2402,
        stack_size:50,
        can_build:true,
        build_index:504,
        description:'The production speed has been greatly improved, and items can be processed more quickly.',
    },
    {id: 2305,
        name:'Assembling Machine Mk.III',
        type:'PRODUCTION',
        grid_index:2403,
        stack_size:50,
        can_build:true,
        build_index:505,
        description:'The production speed is maximized, and a reasonable combination of conveyor belts and sorters of different speeds can effectively avoid the empty assembler or product blockage.',
    },
    {id: 2306,
        name:'Water Pump',
        type:'PRODUCTION',
        grid_index:2306,
        stack_size:30,
        can_build:true,
        build_index:203,
        description:'Facility used to collect liquid resources from an ocean, including water and sulfuric acid.',
    },
    {id: 2307,
        name:'Oil Extractor',
        type:'PRODUCTION',
        grid_index:2307,
        stack_size:20,
        can_build:true,
        build_index:204,
        description:'When plasma is used to extract oil from the Crude oil seep, the extraction speed will be different for different Crude oil seep.',
    },
    {id: 2308,
        name:'Oil Refinery',
        type:'PRODUCTION',
        grid_index:2308,
        stack_size:30,
        can_build:true,
        build_index:507,
        description:'The extracted crude oil is further refined to obtain refined oil and hydrogen.',
    },
    {id: 2309,
        name:'Chemical Plant',
        type:'PRODUCTION',
        grid_index:2408,
        stack_size:30,
        can_build:true,
        build_index:508,
        description:'Chemical facility. Can process the primary products of Crude oil into more advanced chemical products.',
    },
    {id: 2310,
        name:'Miniature Particle Collider',
        type:'PRODUCTION',
        grid_index:2309,
        stack_size:20,
        can_build:true,
        build_index:510,
        description:'When the two beams of particles are continuously accelerated to a certain intensity and energy, they will collide, and new particles can be obtained. It is usually used to stably produce deuterium and antimatter, but will consume a lot of energy.',
    },
    {id: 2311,
        name:'EM-Rail Ejector',
        type:'PRODUCTION',
        grid_index:2310,
        stack_size:30,
        can_build:true,
        build_index:801,
        description:"Launch a large amount of solar sails into the orbit of the system's star to form a Dyson Swarm.",
    },
    {id: 2312,
        name:'Vertical Launching Silo',
        type:'PRODUCTION',
        grid_index:2311,
        stack_size:10,
        can_build:true,
        build_index:803,
        description:'Launch a small carrier rocket loaded with Dyson sphere components onto the Dyson sphere orbit to form nodes and frames.',
    },
    {id: 2313,
        name:'Spray Coater',
        type:'PRODUCTION',
        grid_index:2406,
        stack_size:50,
        can_build:true,
        build_index:506,
        description:'After setting up the Spray Coater on the conveyor belt and inputting the Proliferator into the sprayer from the upper port, the cargos carried on the conveyor belt can be sprayed with the Proliferator. When the cargos are used as raw materials for the next level of production, it can obtain the effect of Extra Products or Production Speedup.',
    },
    {id: 2314,
        name:'Fractionator',
        type:'PRODUCTION',
        grid_index:2407,
        stack_size:30,
        can_build:true,
        build_index:509,
        description:'Taking advantage of the high vapor pressure ratio of liquid hydrogen and liquid deuterium at a certain temperature, deuterium is fractionated from liquid hydrogen with a certain separation efficiency. Use a conveyor belt to introduce hydrogen from one side, after fractional distillation, export from the other side, and export the deuterium from the front port.',
    },
    {id: 2315,
        name:'Plane Smelter',
        type:'PRODUCTION',
        grid_index:2405,
        stack_size:50,
        can_build:true,
        build_index:502,
        description:'When monopoles pass through the Plane Filter, they produce a quantum effect of self-organizing and can generate a thermodynamic negative temperature flow. Using this technology, the process of ores smelting or purification can be greatly accelerated.',
    },
    {id: 2316,
        name:'Advanced Mining Machine',
        type:'PRODUCTION',
        grid_index:2305,
        stack_size:30,
        sub_id:2,
        can_build:true,
        build_index:202,
        description:'Using the quantum chip to positively intervene the photon group generated by the exciter in the transition process, it can lead a obvious bunching effect of the laser beam. Under the action of the special gravitational field, the focused laser beam rapidly heats the ore veins along the predetermined path, transports in the form of particles and encapsulated into cargos. it can be built more convenient and have a higher gathering speed. The collected ores can be transported out by conveyor belts or logistics drones.',
    },
    {id: 2901,
        name:'Matrix Lab',
        type:'PRODUCTION',
        grid_index:2409,
        stack_size:50,
        can_build:true,
        build_index:701,
        description:'Connector to the CenterBrain. Used to both produce matrices and research technologies. The more matrix labs, the faster production or research speed can progress.',
    },
    {id: 5001,
        name:'Logistics Drone',
        type:'LOGISTICS',
        grid_index:1511,
        stack_size:200,
        description:'It can dynamically balance the supply and demand in the planetary logistics system, but it will only work for the logistics station it belongs to.',
    },
    {id: 5002,
        name:'Logistics Vessel',
        type:'LOGISTICS',
        grid_index:1611,
        stack_size:50,
        description:'It can dynamically balance the supply and demand of cargo between planets, and consumes space warper can activate warp.',
    },
    {id: 6001,
        name:'Electromagnetic Matrix',
        type:'MATRIX',
        grid_index:1701,
        stack_size:200,
        description:'One of the five basic source codes that keep the CentreBrain simulating, is the foundation of all scientific and technological research.',
    },
    {id: 6002,
        name:'Energy Matrix',
        type:'MATRIX',
        grid_index:1702,
        stack_size:200,
        description:'One of the five basic source codes that keep the CentreBrain simulating, the emergence of the energy matrix has largely promoted the further development of technology.',
    },
    {id: 6003,
        name:'Structure Matrix',
        type:'MATRIX',
        grid_index:1703,
        stack_size:200,
        description:'One of the five basic source codes that keep the CentreBrain simulating, can be used to unlock more advanced new structural materials.',
    },
    {id: 6004,
        name:'Information Matrix',
        type:'MATRIX',
        grid_index:1704,
        stack_size:200,
        description:'One of the five basic source codes that keep the CentreBrain simulating, the level of informatization will largely affect the production efficiency of the base.',
    },
    {id: 6005,
        name:'Gravity Matrix',
        type:'MATRIX',
        grid_index:1705,
        stack_size:200,
        description:'One of the five basic source codes that keep the CentreBrain simulating, to some extent, unifies quantum field theory and general relativity.',
    },
    {id: 6006,
        name:'Universe Matrix',
        type:'MATRIX',
        grid_index:1706,
        stack_size:200,
        description:'Includes everything, the final answer to the theory of everything, solving the ultimate mystery of the universe!',
    },
]


let game_recipes = [
    {
        id:5,
        name:'Gear',
        type:'ASSEMBLE',
        outputs: [1201, 1],
        inputs: [1101, 1],
        handcraft:true,
        seconds:1,
    },{
        id:6,
        name:'Magnetic Coil',
        type:'ASSEMBLE',
        outputs: [1202, 2],
        inputs: [1102, 2, 1104, 1],
        handcraft:true,
        seconds:1,
    },{
        id:11,
        name:'Prism',
        type:'ASSEMBLE',
        outputs: [1111, 2],
        inputs: [1110, 3],
        handcraft:true,
        seconds:2,
    },{
        id:12,
        name:'Plasma Exciter',
        type:'ASSEMBLE',
        outputs: [1401, 1],
        inputs: [1202, 4, 1111, 2],
        handcraft:true,
        seconds:2,
    },{
        id:19,
        name:'Hydrogen Fuel Rod',
        type:'ASSEMBLE',
        outputs: [1801, 2],
        inputs: [1106, 1, 1120, 10],
        handcraft:true,
        seconds:6,
    },{
        id:20,
        name:' - Thruster',
        type:'ASSEMBLE',
        outputs: [1405, 1],
        inputs: [1103, 2, 1104, 3],
        handcraft:true,
        seconds:4,
    },{
        id:21,
        name:'Reinforced Thruster',
        type:'ASSEMBLE',
        outputs: [1406, 1],
        inputs: [1107, 5, 1204, 5],
        handcraft:true,
        seconds:6,
    },{
        id:26,
        name:'Titanium Crystal',
        type:'ASSEMBLE',
        outputs: [1118, 1],
        inputs: [1117, 1, 1106, 3],
        handcraft:true,
        seconds:4,
    },{
        id:28,
        name:'Casimir Crystal',
        type:'ASSEMBLE',
        outputs: [1126, 1],
        inputs: [1118, 1, 1123, 2, 1120, 12],
        handcraft:true,
        seconds:4,
    },{
        id:29,
        name:'Casimir Crystal (Advanced)',
        type:'ASSEMBLE',
        outputs: [1126, 1],
        inputs: [1014, 4, 1123, 2, 1120, 12],
        handcraft:false,
        seconds:4,
        explicit:true,
        description:'The use of rare ore optical grating crystal to make Casimir crystal is more efficient.',
    },{
        id:30,
        name:'Titanium Glass',
        type:'ASSEMBLE',
        outputs: [1119, 2],
        inputs: [1110, 2, 1106, 2, 1000, 2],
        handcraft:true,
        seconds:5,
    },{
        id:36,
        name:'Particle Broadband',
        type:'ASSEMBLE',
        outputs: [1402, 1],
        inputs: [1124, 2, 1113, 2, 1115, 1],
        handcraft:true,
        seconds:8,
    },{
        id:38,
        name:'Plane Filter',
        type:'ASSEMBLE',
        outputs: [1304, 1],
        inputs: [1126, 1, 1119, 2],
        handcraft:true,
        seconds:12,
    },{
        id:41,
        name:'Deuteron Fuel Rod',
        type:'ASSEMBLE',
        outputs: [1802, 2],
        inputs: [1107, 1, 1121, 20, 1205, 1],
        handcraft:true,
        seconds:12,
    },{
        id:42,
        name:'Annihilation Constraint Sphere',
        type:'ASSEMBLE',
        outputs: [1403, 1],
        inputs: [1206, 1, 1303, 1],
        handcraft:true,
        seconds:20,
    },{
        id:44,
        name:'Antimatter Fuel Rod',
        type:'ASSEMBLE',
        outputs: [1803, 2],
        inputs: [1122, 12, 1120, 12, 1403, 1, 1107, 1],
        handcraft:false,
        seconds:24,
    },{
        id:50,
        name:'Circuit Board',
        type:'ASSEMBLE',
        outputs: [1301, 2],
        inputs: [1101, 2, 1104, 1],
        handcraft:true,
        seconds:1,
    },{
        id:51,
        name:'Processor',
        type:'ASSEMBLE',
        outputs: [1303, 1],
        inputs: [1301, 2, 1302, 2],
        handcraft:true,
        seconds:3,
    },{
        id:52,
        name:'Quantum Chip',
        type:'ASSEMBLE',
        outputs: [1305, 1],
        inputs: [1303, 2, 1304, 2],
        handcraft:true,
        seconds:6,
    },{
        id:53,
        name:'Microcrystalline Component',
        type:'ASSEMBLE',
        outputs: [1302, 1],
        inputs: [1105, 2, 1104, 1],
        handcraft:true,
        seconds:2,
    },{
        id:54,
        name:'Organic Crystal (Original)',
        type:'ASSEMBLE',
        outputs: [1117, 1],
        inputs: [1030, 20, 1031, 30, 1000, 10],
        handcraft:true,
        seconds:6,
        explicit:true,
        description:'Organic crystal can be obtained by processing the three resources of wood, plant fuel and water.',
    },{
        id:62,
        name:'Crystal Silicon (Advanced)',
        type:'ASSEMBLE',
        outputs: [1113, 2],
        inputs: [1013, 1],
        handcraft:false,
        seconds:1.5,
        explicit:true,
        description:'The unique fractal structure of Fractal silicon is the material of choice for the efficient production of Crystal silicon.',
    },{
        id:68,
        name:'Photon Combiner',
        type:'ASSEMBLE',
        outputs: [1404, 1],
        inputs: [1111, 2, 1301, 1],
        handcraft:true,
        seconds:3,
    },{
        id:69,
        name:'Photon Combiner (Advanced)',
        type:'ASSEMBLE',
        outputs: [1404, 1],
        inputs: [1014, 1, 1301, 1],
        handcraft:false,
        seconds:3,
        explicit:true,
        description:'The discovery of optical grating crystal has diversified the production of Photon combiner.',
    },{
        id:70,
        name:'Solar Sail',
        type:'ASSEMBLE',
        outputs: [1501, 2],
        inputs: [1123, 1, 1404, 1],
        handcraft:true,
        seconds:4,
    },{
        id:78,
        name:'Space Warper',
        type:'ASSEMBLE',
        outputs: [1210, 1],
        inputs: [1209, 1],
        handcraft:true,
        seconds:10,
    },{
        id:79,
        name:'Space Warper (Advanced)',
        type:'ASSEMBLE',
        outputs: [1210, 8],
        inputs: [6005, 1],
        handcraft:true,
        seconds:10,
        explicit:true,
        description:'With the Gravity matrix, the production of the space warper becomes easier.',
    },{
        id:80,
        name:'Frame Material',
        type:'ASSEMBLE',
        outputs: [1125, 1],
        inputs: [1124, 4, 1107, 1, 1105, 1],
        handcraft:true,
        seconds:6,
    },{
        id:81,
        name:'Dyson Sphere Component',
        type:'ASSEMBLE',
        outputs: [1502, 1],
        inputs: [1125, 3, 1501, 3, 1303, 3],
        handcraft:true,
        seconds:8,
    },{
        id:83,
        name:'Small Carrier Rocket',
        type:'ASSEMBLE',
        outputs: [1503, 1],
        inputs: [1502, 2, 1802, 4, 1305, 2],
        handcraft:true,
        seconds:6,
    },{
        id:94,
        name:'Logistics Drone',
        type:'ASSEMBLE',
        outputs: [5001, 1],
        inputs: [1101, 5, 1303, 2, 1405, 2],
        handcraft:true,
        seconds:4,
    },{
        id:96,
        name:'Logistics Vessel',
        type:'ASSEMBLE',
        outputs: [5002, 1],
        inputs: [1107, 10, 1303, 10, 1406, 2],
        handcraft:true,
        seconds:6,
    },{
        id:97,
        name:'Electric Motor',
        type:'ASSEMBLE',
        outputs: [1203, 1],
        inputs: [1101, 2, 1201, 1, 1202, 1],
        handcraft:true,
        seconds:2,
    },{
        id:98,
        name:'Electromagnetic Turbine',
        type:'ASSEMBLE',
        outputs: [1204, 1],
        inputs: [1203, 2, 1202, 2],
        handcraft:true,
        seconds:2,
    },{
        id:99,
        name:'Particle Container',
        type:'ASSEMBLE',
        outputs: [1206, 1],
        inputs: [1204, 2, 1104, 2, 1123, 2],
        handcraft:true,
        seconds:4,
    },{
        id:100,
        name:'Particle Container (Advanced)',
        type:'ASSEMBLE',
        outputs: [1206, 1],
        inputs: [1016, 10, 1104, 2],
        handcraft:false,
        seconds:4,
        explicit:true,
        description:'Although the Unipolar magnet is extremely rare, as long as you find it, you can make Particle container more efficiently.',
    },{
        id:101,
        name:'Graviton Lens',
        type:'ASSEMBLE',
        outputs: [1209, 1],
        inputs: [1112, 4, 1127, 1],
        handcraft:true,
        seconds:6,
    },{
        id:103,
        name:'Super-Magnetic Ring',
        type:'ASSEMBLE',
        outputs: [1205, 1],
        inputs: [1204, 2, 1102, 3, 1109, 1],
        handcraft:true,
        seconds:3,
    },{
        id:106,
        name:'Proliferator Mk.I',
        type:'ASSEMBLE',
        outputs: [1141, 1],
        inputs: [1006, 1],
        handcraft:true,
        seconds:'.5',
    },{
        id:107,
        name:'Proliferator Mk.II',
        type:'ASSEMBLE',
        outputs: [1142, 1],
        inputs: [1141, 2, 1112, 1],
        handcraft:true,
        seconds:1,
    },{
        id:108,
        name:'Proliferator Mk.III',
        type:'ASSEMBLE',
        outputs: [1143, 1],
        inputs: [1142, 2, 1124, 1],
        handcraft:true,
        seconds:2,
    },{
        id:112,
        name:'Foundation',
        type:'ASSEMBLE',
        outputs: [1131, 1],
        inputs: [1108, 3, 1103, 1],
        handcraft:true,
        seconds:1,
    },{
        id:23,
        name:'Plastic',
        type:'CHEMICAL',
        outputs: [1115, 1],
        inputs: [1114, 2, 1109, 1],
        handcraft:false,
        seconds:3,
    },{
        id:24,
        name:'Sulfuric Acid',
        type:'CHEMICAL',
        outputs: [1116, 4],
        inputs: [1114, 6, 1005, 8, 1000, 4],
        handcraft:false,
        seconds:6,
    },{
        id:25,
        name:'Organic Crystal',
        type:'CHEMICAL',
        outputs: [1117, 1],
        inputs: [1115, 2, 1114, 1, 1000, 1],
        handcraft:false,
        seconds:6,
    },{
        id:31,
        name:'Graphene',
        type:'CHEMICAL',
        outputs: [1123, 2],
        inputs: [1109, 3, 1116, 1],
        handcraft:false,
        seconds:3,
    },{
        id:32,
        name:'Graphene (Advanced)',
        type:'CHEMICAL',
        outputs: [1123, 2, 1120, 1],
        inputs: [1011, 2],
        handcraft:false,
        seconds:2,
        explicit:true,
        description:'It will be a lot easier to produce graphene if you can find combustible ice minerals.',
    },{
        id:33,
        name:'Carbon Nanotube',
        type:'CHEMICAL',
        outputs: [1124, 2],
        inputs: [1123, 3, 1106, 1],
        handcraft:false,
        seconds:4,
    },{
        id:35,
        name:'Carbon Nanotube (Advanced)',
        type:'CHEMICAL',
        outputs: [1124, 2],
        inputs: [1015, 2],
        handcraft:false,
        seconds:4,
        explicit:true,
        description:'Carbon nanotube can be made directly from spiniform stalagmite crystal, but this ore is extremely rare and difficult to find.',
    },{
        id:115,
        name:'Deuterium Fractionation',
        type:'FRACTIONATE',
        outputs: [1121, 0.01, 1120, 0.99],
        inputs: [1120, 1.0],
        handcraft:false,
        seconds:'.017',
        explicit:true,
        description:'The successful fractionation of deuterium from liquid hydrogen has greatly promoted the use of nuclear fuel.',
    },{
        id:40,
        name:'Deuterium',
        type:'PARTICLE',
        outputs: [1121, 5],
        inputs: [1120, 10],
        handcraft:false,
        seconds:2.5,
    },{
        id:74,
        name:'Mass-Energy Storage',
        type:'PARTICLE',
        outputs: [1122, 2, 1120, 2],
        inputs: [1208, 2],
        handcraft:false,
        seconds:2,
        explicit:true,
        description:'Photons can be inverted into antimatter and hydrogen under the effect of super magnetic field.',
    },{
        id:104,
        name:'Strange Matter',
        type:'PARTICLE',
        outputs: [1127, 1],
        inputs: [1206, 2, 1101, 2, 1121, 10],
        handcraft:false,
        seconds:8,
    },{
        id:16,
        name:'Plasma Refining',
        type:'REFINE',
        outputs: [1120, 1, 1114, 2],
        inputs: [1007, 2],
        handcraft:false,
        seconds:4,
        explicit:true,
        description:'Hydrogen and refined oil can be obtained by refining crude oil with plasma.',
    },{
        id:58,
        name:'X-Ray Cracking',
        type:'REFINE',
        outputs: [1120, 3, 1109, 1],
        inputs: [1114, 1, 1120, 2],
        handcraft:false,
        seconds:4,
        explicit:true,
        description:'Under the catalysis of hydrogen, X-rays can crack the refined oil into more hydrogen and a by-product, energetic graphite.',
    },{
        id:9,
        name:'Electromagnetic Matrix',
        type:'RESEARCH',
        outputs: [6001, 1],
        inputs: [1202, 1, 1301, 1],
        handcraft:true,
        seconds:3,
    },{
        id:18,
        name:'Energy Matrix',
        type:'RESEARCH',
        outputs: [6002, 1],
        inputs: [1109, 2, 1120, 2],
        handcraft:true,
        seconds:6,
    },{
        id:27,
        name:'Structure Matrix',
        type:'RESEARCH',
        outputs: [6003, 1],
        inputs: [1112, 1, 1118, 1],
        handcraft:true,
        seconds:8,
    },{
        id:55,
        name:'Information Matrix',
        type:'RESEARCH',
        outputs: [6004, 1],
        inputs: [1303, 2, 1402, 1],
        handcraft:true,
        seconds:10,
    },{
        id:102,
        name:'Gravity Matrix',
        type:'RESEARCH',
        outputs: [6005, 2],
        inputs: [1209, 1, 1305, 1],
        handcraft:true,
        seconds:24,
    },{
        id:75,
        name:'Universe Matrix',
        type:'RESEARCH',
        outputs: [6006, 1],
        inputs: [6001, 1, 6002, 1, 6003, 1, 6004, 1, 6005, 1, 1122, 1],
        handcraft:false,
        seconds:15,
    },{
        id:1,
        name:'Iron Ingot',
        type:'SMELT',
        outputs: [1101, 1],
        inputs: [1001, 1],
        handcraft:true,
        seconds:1,
    },{
        id:2,
        name:'Magnet',
        type:'SMELT',
        outputs: [1102, 1],
        inputs: [1001, 1],
        handcraft:true,
        seconds:1.5,
    },{
        id:3,
        name:'Copper Ingot',
        type:'SMELT',
        outputs: [1104, 1],
        inputs: [1002, 1],
        handcraft:true,
        seconds:1,
    },{
        id:4,
        name:'Stone Brick',
        type:'SMELT',
        outputs: [1108, 1],
        inputs: [1005, 1],
        handcraft:true,
        seconds:1,
    },{
        id:17,
        name:'Energetic Graphite',
        type:'SMELT',
        outputs: [1109, 1],
        inputs: [1006, 2],
        handcraft:true,
        seconds:2,
    },{
        id:34,
        name:'Silicon Ore',
        type:'SMELT',
        outputs: [1003, 1],
        inputs: [1005, 10],
        handcraft:false,
        seconds:10,
    },{
        id:37,
        name:'Crystal Silicon',
        type:'SMELT',
        outputs: [1113, 1],
        inputs: [1105, 1],
        handcraft:false,
        seconds:2,
    },{
        id:57,
        name:'Glass',
        type:'SMELT',
        outputs: [1110, 1],
        inputs: [1005, 2],
        handcraft:true,
        seconds:2,
    },{
        id:59,
        name:'High-Purity Silicon',
        type:'SMELT',
        outputs: [1105, 1],
        inputs: [1003, 2],
        handcraft:true,
        seconds:2,
    },{
        id:60,
        name:'Diamond',
        type:'SMELT',
        outputs: [1112, 1],
        inputs: [1109, 1],
        handcraft:false,
        seconds:2,
    },{
        id:61,
        name:'Diamond (Advanced)',
        type:'SMELT',
        outputs: [1112, 2],
        inputs: [1012, 1],
        handcraft:false,
        seconds:1.5,
        explicit:true,
        description:'Find Kimberlite ore and smelt directly to obtain diamond.',
    },{
        id:63,
        name:'Steel',
        type:'SMELT',
        outputs: [1103, 1],
        inputs: [1101, 3],
        handcraft:false,
        seconds:3,
    },{
        id:65,
        name:'Titanium Ingot',
        type:'SMELT',
        outputs: [1106, 1],
        inputs: [1004, 2],
        handcraft:true,
        seconds:2,
    },{
        id:66,
        name:'Titanium Alloy',
        type:'SMELT',
        outputs: [1107, 4],
        inputs: [1106, 4, 1103, 4, 1116, 8],
        handcraft:false,
        seconds:12,
    },{
        id:7,
        name:'Wind Turbine',
        type:'ASSEMBLE',
        outputs: [2203, 1],
        inputs: [1101, 6, 1201, 1, 1202, 3],
        handcraft:true,
        seconds:4,
    },{
        id:8,
        name:'Tesla Tower',
        type:'ASSEMBLE',
        outputs: [2201, 1],
        inputs: [1101, 2, 1202, 1],
        handcraft:true,
        seconds:1,
    },{
        id:10,
        name:'Matrix Lab',
        type:'ASSEMBLE',
        outputs: [2901, 1],
        inputs: [1101, 8, 1110, 4, 1301, 4, 1202, 4],
        handcraft:true,
        seconds:3,
    },{
        id:13,
        name:'Wireless Power Tower',
        type:'ASSEMBLE',
        outputs: [2202, 1],
        inputs: [2201, 1, 1401, 3],
        handcraft:true,
        seconds:3,
    },{
        id:14,
        name:'Oil Extractor',
        type:'ASSEMBLE',
        outputs: [2307, 1],
        inputs: [1103, 12, 1108, 12, 1301, 6, 1401, 4],
        handcraft:true,
        seconds:8,
    },{
        id:15,
        name:'Oil Refinery',
        type:'ASSEMBLE',
        outputs: [2308, 1],
        inputs: [1103, 10, 1108, 10, 1301, 6, 1401, 6],
        handcraft:true,
        seconds:6,
    },{
        id:22,
        name:'Chemical Plant',
        type:'ASSEMBLE',
        outputs: [2309, 1],
        inputs: [1103, 8, 1108, 8, 1110, 8, 1301, 2],
        handcraft:true,
        seconds:5,
    },{
        id:39,
        name:'Miniature Particle Collider',
        type:'ASSEMBLE',
        outputs: [2310, 1],
        inputs: [1107, 20, 1125, 20, 1205, 50, 1123, 10, 1303, 8],
        handcraft:true,
        seconds:15,
    },{
        id:43,
        name:'Artificial Star',
        type:'ASSEMBLE',
        outputs: [2210, 1],
        inputs: [1107, 20, 1125, 20, 1403, 10, 1305, 10],
        handcraft:true,
        seconds:30,
    },{
        id:45,
        name:'Assembling Machine Mk.I',
        type:'ASSEMBLE',
        outputs: [2303, 1],
        inputs: [1101, 4, 1201, 8, 1301, 4],
        handcraft:true,
        seconds:2,
    },{
        id:46,
        name:'Assembling Machine Mk.II',
        type:'ASSEMBLE',
        outputs: [2304, 1],
        inputs: [2303, 1, 1123, 8, 1303, 4],
        handcraft:true,
        seconds:3,
    },{
        id:47,
        name:'Assembling Machine Mk.III',
        type:'ASSEMBLE',
        outputs: [2305, 1],
        inputs: [2304, 1, 1402, 8, 1305, 2],
        handcraft:true,
        seconds:4,
    },{
        id:48,
        name:'Mining Machine',
        type:'ASSEMBLE',
        outputs: [2301, 1],
        inputs: [1101, 4, 1301, 2, 1202, 2, 1201, 2],
        handcraft:true,
        seconds:3,
    },{
        id:49,
        name:'Water Pump',
        type:'ASSEMBLE',
        outputs: [2306, 1],
        inputs: [1101, 8, 1108, 4, 1203, 4, 1301, 2],
        handcraft:true,
        seconds:4,
    },{
        id:56,
        name:'Arc Smelter',
        type:'ASSEMBLE',
        outputs: [2302, 1],
        inputs: [1101, 4, 1108, 2, 1301, 4, 1202, 2],
        handcraft:true,
        seconds:3,
    },{
        id:64,
        name:'Thermal Power Plant',
        type:'ASSEMBLE',
        outputs: [2204, 1],
        inputs: [1101, 10, 1108, 4, 1201, 4, 1202, 4],
        handcraft:true,
        seconds:5,
    },{
        id:67,
        name:'Solar Panel',
        type:'ASSEMBLE',
        outputs: [2205, 1],
        inputs: [1104, 10, 1105, 10, 1301, 5],
        handcraft:true,
        seconds:6,
    },{
        id:71,
        name:'EM-Rail Ejector',
        type:'ASSEMBLE',
        outputs: [2311, 1],
        inputs: [1103, 20, 1201, 20, 1303, 5, 1205, 10],
        handcraft:true,
        seconds:6,
    },{
        id:72,
        name:'Ray Receiver',
        type:'ASSEMBLE',
        outputs: [2208, 1],
        inputs: [1103, 20, 1105, 20, 1404, 10, 1303, 5, 1205, 20],
        handcraft:true,
        seconds:8,
    },{
        id:73,
        name:'Satellite Substation',
        type:'ASSEMBLE',
        outputs: [2212, 1],
        inputs: [2202, 1, 1205, 10, 1125, 2],
        handcraft:true,
        seconds:5,
    },{
        id:76,
        name:'Accumulator',
        type:'ASSEMBLE',
        outputs: [2206, 1],
        inputs: [1101, 6, 1205, 1, 1113, 6],
        handcraft:true,
        seconds:5,
    },{
        id:77,
        name:'Energy Exchanger',
        type:'ASSEMBLE',
        outputs: [2209, 1],
        inputs: [1107, 40, 1103, 40, 1303, 40, 1206, 8],
        handcraft:true,
        seconds:15,
    },{
        id:82,
        name:'Vertical Launching Silo',
        type:'ASSEMBLE',
        outputs: [2312, 1],
        inputs: [1107, 80, 1125, 30, 1209, 20, 1305, 10],
        handcraft:true,
        seconds:30,
    },{
        id:84,
        name:'Conveyor Belt MK.I',
        type:'ASSEMBLE',
        outputs: [2001, 3],
        inputs: [1101, 2, 1201, 1],
        handcraft:true,
        seconds:1,
    },{
        id:89,
        name:'Conveyor Belt MK.II',
        type:'ASSEMBLE',
        outputs: [2002, 3],
        inputs: [2001, 3, 1204, 1],
        handcraft:true,
        seconds:1,
    },{
        id:92,
        name:'Conveyor Belt MK.III',
        type:'ASSEMBLE',
        outputs: [2003, 3],
        inputs: [2002, 3, 1205, 1, 1123, 1],
        handcraft:true,
        seconds:1,
    },{
        id:85,
        name:'Sorter MK.I',
        type:'ASSEMBLE',
        outputs: [2011, 1],
        inputs: [1101, 1, 1301, 1],
        handcraft:true,
        seconds:1,
    },{
        id:88,
        name:'Sorter MK.II',
        type:'ASSEMBLE',
        outputs: [2012, 2],
        inputs: [2011, 2, 1203, 1],
        handcraft:true,
        seconds:1,
    },{
        id:90,
        name:'Sorter MK.III',
        type:'ASSEMBLE',
        outputs: [2013, 2],
        inputs: [2012, 2, 1204, 1],
        handcraft:true,
        seconds:1,
    },{
        id:86,
        name:'Storage MK.I',
        type:'ASSEMBLE',
        outputs: [2101, 1],
        inputs: [1101, 4, 1108, 4],
        handcraft:true,
        seconds:2,
    },{
        id:91,
        name:'Storage MK.II',
        type:'ASSEMBLE',
        outputs: [2102, 1],
        inputs: [1103, 8, 1108, 8],
        handcraft:true,
        seconds:4,
    },{
        id:87,
        name:'Splitter',
        type:'ASSEMBLE',
        outputs: [2020, 1],
        inputs: [1101, 3, 1201, 2, 1301, 1],
        handcraft:true,
        seconds:2,
    },{
        id:93,
        name:'Planetary Logistics Station',
        type:'ASSEMBLE',
        outputs: [2103, 1],
        inputs: [1103, 40, 1106, 40, 1303, 40, 1206, 20],
        handcraft:true,
        seconds:20,
    },{
        id:95,
        name:'Interstellar Logistics Station',
        type:'ASSEMBLE',
        outputs: [2104, 1],
        inputs: [2103, 1, 1107, 40, 1206, 20],
        handcraft:true,
        seconds:30,
    },{
        id:109,
        name:'Spray Coater',
        type:'ASSEMBLE',
        outputs: [2313, 1],
        inputs: [1103, 4, 1401, 2, 1301, 2, 1302, 2],
        handcraft:true,
        seconds:3,
    },{
        id:110,
        name:'Fractionator',
        type:'ASSEMBLE',
        outputs: [2314, 1],
        inputs: [1103, 8, 1108, 4, 1110, 4, 1303, 1],
        handcraft:true,
        seconds:3,
    },{
        id:111,
        name:'Orbital Collector',
        type:'ASSEMBLE',
        outputs: [2105, 1],
        inputs: [2104, 1, 1205, 50, 1406, 20, 2207, 20],
        handcraft:true,
        seconds:30,
    },{
        id:113,
        name:'Mini Fusion Power Plant',
        type:'ASSEMBLE',
        outputs: [2211, 1],
        inputs: [1107, 12, 1205, 10, 1124, 8, 1303, 4],
        handcraft:true,
        seconds:10,
    },{
        id:114,
        name:'Storage Tank',
        type:'ASSEMBLE',
        outputs: [2106, 1],
        inputs: [1101, 8, 1108, 4, 1110, 4],
        handcraft:true,
        seconds:2,
    },{
        id:116,
        name:'Plane Smelter',
        type:'ASSEMBLE',
        outputs: [2315, 1],
        inputs: [2302, 1, 1125, 5, 1304, 4, 1016, 15],
        handcraft:true,
        seconds:5,
    },{
        id:117,
        name:'Traffic Monitor',
        type:'ASSEMBLE',
        outputs: [2030, 1],
        inputs: [1101, 3, 1201, 2, 1110, 1, 1301, 2],
        handcraft:true,
        seconds:2,
    },{
        id:118,
        name:'Geothermal Power Station',
        type:'ASSEMBLE',
        outputs: [2213, 1],
        inputs: [1103, 15, 1104, 20, 1404, 4, 1205, 1],
        handcraft:true,
        seconds:6,
    },{
        id:119,
        name:'Advanced Mining Machine',
        type:'ASSEMBLE',
        outputs: [2316, 1],
        inputs: [1107, 20, 1125, 10, 1205, 10, 1305, 4, 1014, 40],
        handcraft:true,
        seconds:20,
    },{
        id:120,
        name:'Automatic Piler',
        type:'ASSEMBLE',
        outputs: [2040, 1],
        inputs: [1103, 3, 1201, 4, 1205, 1, 1303, 2],
        handcraft:true,
        seconds:4,
    },
]

window.game_items = game_items
window.game_recipes = game_recipes

let recipes = []
recipes.push(...game_items
    .filter(item => item.type === 'RESOURCE')
    .map((rawItem) => {
        return {
            name: rawItem.name,
            altName: null,
            ingredients: []
        }
    })
)


game_recipes.forEach((rawRecipe) => {
    if (rawRecipe.outputs.length > 2) {
        return recipes.push(...splitter(rawRecipe))
    }

    recipes.push(remapRecipe(rawRecipe))
})


function remapRecipe(rawRecipe) {
    let ingredients = []
    let outputItem = _.find(game_items, {id: rawRecipe.outputs[0]})
    let outputQuantity = rawRecipe.outputs[1]
    _.chunk(rawRecipe.inputs, 2).forEach((input) => {
        let inputItem = _.find(game_items, {id: input[0]})
        let quantity = input[1]/outputQuantity
        ingredients.push({name: inputItem.name, quantity})
    })
    let altName = rawRecipe.name.includes("(Advanced)") ? rawRecipe.name : null

    return {
        name: outputItem.name,
        altName,
        ingredients
    }
}


function splitter(rawRecipe) {
    if (rawRecipe.name === 'Deuterium Fractionation') {
        let outputItem = _.find(game_items, {id: 1121})
        let inputItem = _.find(game_items, {id: 1120})
        let ingredients = [{name: inputItem.name, quantity: 1}]
        return [{name: outputItem.name, altName: null, ingredients}]
    }

    let recipes = []
    let outputs = _.chunk(rawRecipe.outputs, 2)
    for (let i=0; i<2; i++) {
        let output = outputs[i]
        let input = [...outputs[1-i]]
        input[1] = -input[1]
        let partialRecipe = _.cloneDeep(rawRecipe)
        partialRecipe.outputs = output
        partialRecipe.inputs = [...partialRecipe.inputs, ...input]
        recipes.push(remapRecipe(partialRecipe))
    }


    return recipes
}





window.dysonRecipes = recipes
// console.log(JSON5.stringify(recipes, null, 2))